### ISSUE TITLE
Select repositories/activity you'd like to receive notifications for

### ISSUE THREAD

**Issue by joeyfigaro** [harksys/HawkEye#10]
There's an awful lot of stuff I don't want to be notified of. Currently no way to parse any of it out / highlight the repositories I *do* want to watch.

**Comment by andrewhathaway** [comment]
Hi @joeyfigaro! Some sort of mute filter per repository might be useful for this. Appreciate the issue!

**Comment by GoldenChaos** [comment]
If this were a feature I would stop using Github's built-in notification system and switch to this full time.

**Comment by bterlson** [comment]
Chiming in to say that this is the feature that will get me on board.

More details of my scenario: I have repos that I need to be subscribed to but only need to check notifications occasionally. Some repos I don't care to get notifications for unless I'm explicitly mentioned. I also would like to be able to group repos so I can eg. click `tc39` and process notifications for all repos under that org.

**Comment by andrewhathaway** [comment]
Good to hear this will help. So from @bterlson requirements, this sounds more complicated than just being able to filter out repositories. Sounds like more complicated mute-rules, unless by default we make it filter by repository unless mentioned?

More complicated mute-rules sounds to me like it could get messy, both from a UI stand point and users accidentally muting everything by having crossing-over rules.

If you could also help me out, and give me your thoughts on what you think would work best for you,  we can work towards the best approach.

**Comment by bterlson** [comment]
@andrewhathaway I think the two things that would be perfect for me are per-repo mute-unless-mentioned (you could also consider check boxes for notification types so eg. I could choose to only be notified about a repo's issues where I'm mentioned or when they release, say), and organization filters.

**Comment by andrewhathaway** [comment]
@bterlson Okay so this could work. Instead of per-repo muting from a whole, or adding a whole filter set, we can just have a set of checkboxes per repository for the Reason and Subject Types. Unchecking will result in muting. How does that sound?

**Comment by bterlson** [comment]
@andrewhathaway It sounds phenomenal, but the typical caveat that the user never knows what he actually wants applies :-P

**Comment by bterlson** [comment]
Also an org filter would be greatly appreciated for people who have to switch hats frequently.

**Comment by andrewhathaway** [comment]
@bterlson Would be great if you could file another for the org filter, as thats a separate concern!

**Comment by andrewhathaway** [comment]
Hi @joeyfigaro @GoldenChaos and @bterlson.

I have created a PR (#21) with the ability to do the mentioned above. If you guys could take a look, then we can get this in and possibly push out a version for you guys to use!

🎉

**Comment by andrewhathaway** [comment]
Closing due to merged #21.
