### ISSUE TITLE
More information on the notification

### ISSUE THREAD

**Issue by bukinoshita** [harksys/HawkEye#11]
I wish I could see more information about the notification itself like a preview of the message posted. For now it's just showing the `title`, `repo` and `type`.

```
[Issue] Issue title
company/repo - updated X hours ago

@username commented:
Lorem ipsum
```

**Comment by andrewhathaway** [comment]
Sure we can take a look in to this. Depending on how many notifications you have, this may cause rate limiting issues. 

Also from a UI stand point, I'd rather that you click "in to" the notifications to a new view which has further details.
