### ISSUE TITLE
Make only top/titlebar dragable

### ISSUE THREAD

**Issue by bnb** [harksys/HawkEye#14]
One issue I've run into a few times in my ~30  minutes of usage of HawkEye is that anywhere I click inside the application allows me to drag the entire window (even if I'm clicking a UI element). Would be 💯 to make this only a specific area of the app (like the sidebar, perhaps).

OS: macOS Sierra
Version: 0.1.0 (`.dmg`)

**Comment by andrewhathaway** [comment]
Currently the left-bar, filter list and title bar are draggable. I currently like the fact that the left bar makes the window draggable, and the title bar. I added dragging to the filter list as I attempted to do so and expected it to be draggable, but it wasn't.

**Comment by andrewhathaway** [comment]
@bnb Okay. I just tried clicking a filter and had an issue with the window moving. I'll remove the dragging from the filter list, and that should resolve this issue.
