### ISSUE TITLE
Enlarge PR/Issue Icons

### ISSUE THREAD

**Issue by bnb** [harksys/HawkEye#15]
Enlarging the PR and Issue icons in feed for a bit of a better visual cue on what type of notification you're looking at in the feed would be awesome.

The icons that I'm specifically referring to: 
![image](https://cloud.githubusercontent.com/assets/502396/21707419/02298a14-d39d-11e6-9a76-1e3d480ff94e.png)

**Comment by andrewhathaway** [comment]
Hi @bnb! Thanks for the issue. We can most certainly look in to this, see what fits and doesn't look to extreme.

**Comment by juliankay** [comment]
+1 I like the idea of increasing the size here
