### ISSUE TITLE
Installation issue regarding the ia32 package.

### ISSUE THREAD

**Issue by klauscfhq** [harksys/HawkEye#22]
Hi! 
I tried installing the **ia32 version** of the app, on a 32bit machine, and the following came out. 
It appears that the .deb is not actually of ia32 architecture, but of **amd64** instead.
Other than that, all other versions can be installed perfectly! :tada: 
Love the project! :heart:  
![screenshot_2017-01-08_19-29-19](https://cloud.githubusercontent.com/assets/12670537/21752008/5d223324-d5d9-11e6-829b-ca1fe8e65ed5.png)

**Comment by andrewhathaway** [comment]
Oh I am sorry for that, this is my mistake renaming for the release server. Did you manage to install any of the other Linux releases? 

I will rename that file for the release.

**Comment by andrewhathaway** [comment]
Renamed to amd64 on the releases.

**Comment by klauscfhq** [comment]
Yep, installing the rest releases on a 64-bit machine is a like breeze :v:

![sketch](https://cloud.githubusercontent.com/assets/12670537/21776755/be36bd8a-d6a4-11e6-9343-87dc8d8f10ca.png)

**Comment by andrewhathaway** [comment]
@klauscfhq Great to hear! You're the first Linux user that has made me aware you're using it, so be sure to file any issues with anything I'm not catering for on Linux, etc!

**Comment by klauscfhq** [comment]
@andrewhathaway No worries! If anything comes up I will definitely share it, after all the app is quite a lot useful and essential regardless of the OS, and I believe that most of its users really appreciate the work done. Also being cross-platform adds a huge advantage compared to other similar project that are around atm, majority of whom are supporting a single OS. So, my thoughts are that your project will grow fast! Again happy to help :)
