### ISSUE TITLE
Cannot scroll through list of notifications

### ISSUE THREAD

**Issue by Baadier-Sydow** [harksys/HawkEye#24]
I am unable to scroll a list of notifications when looking at a repository with a large amount of notifications.

-

Hawk Eye 0.2.0
Electron 1.4.11
darwin x64 16.1.0

**Comment by andrewhathaway** [comment]
Hi there. This is the first I've heard of this, I can't think of any reason why this would happen unless you have something configured on your machine, of which I can't replicate.

Just to confirm, are you attempting to scroll using a mouse? Any further details would help.

**Comment by Baadier-Sydow** [comment]
I tested it again now and it's working with both my mouse and keyboard.

What I have noticed is that there was no scrollbar on the list of notifications when I was using it yesterday.

**Comment by andrewhathaway** [comment]
Interesting. Well I'm glad it works!
