### ISSUE TITLE
Error when closing all notifications

### ISSUE THREAD

**Issue by Baadier-Sydow** [harksys/HawkEye#25]
I get the following error when I had a specific repository selected and clicked the "Clear All" icon.

**A JavaScript error occurred in the main process**

> Uncaught Exception:
> TypeError: Cannot read property 'statusCode' of undefined
>     at Request._callback (/Applications/Hawk Eye.app/Contents/Resources/app.asar/main.js:234:21)
>     at self.callback (/Applications/Hawk Eye.app/Contents/Resources/app.asar/node_modules/request/request.js:186:22)
>     at emitOne (events.js:96:13)
>     at Request.emit (events.js:188:7)
>     at Request.onRequestError (/Applications/Hawk Eye.app/Contents/Resources/app.asar/node_modules/request/request.js:845:8)
>     at emitOne (events.js:96:13)
>     at ClientRequest.emit (events.js:188:7)
>     at TLSSocket.socketErrorListener (_http_client.js:308:9)
>     at emitOne (events.js:96:13)
>     at TLSSocket.emit (events.js:188:7)

The error dialog repeated a handful of times when I dismissed it.

**Comment by andrewhathaway** [comment]
Thank you for the issue. This must have been during GitHubs down time earlier. I will patch this up shortly.
