### ISSUE TITLE
How do notifications work?

### ISSUE THREAD

**Issue by decadence** [harksys/HawkEye#26]
Hello.
Thanks for great app.
But I don't quite understand how it works. I have 1 new notification on GitHub Notification page.
![screenshot_1](https://cloud.githubusercontent.com/assets/1434668/26755491/e9227070-4896-11e7-984c-213226d80c2e.png)

But I can't see it in app and I don't get any popup windows for new notification.
![screenshot_2](https://cloud.githubusercontent.com/assets/1434668/26755511/351a56e6-4897-11e7-8566-a8c48ce28a83.png)

Update frequency is 5 minutes. Am I doing something wrong?

Moreover it shows me notifications which I already read as you can see.
Even restart doesn't help.

Windows 10 x64.
No firewall, no antivirus.

**Comment by decadence** [comment]
Seems like it updates only after login once

**Comment by andrewhathaway** [comment]
@decadence That shouldn't be the case, it's constantly updating. Read notifications still get imported in to Hawk Eye, also check your settings for how often it's polling!

**Comment by decadence** [comment]
Update frequency is 5 minutes as I said.
However that's the case for me and I have no idea why is this closed.
Tomorrow I will check it on another PC.

**Comment by andrewhathaway** [comment]
This could be a potential issue if your computer is sleeping and Hawk Eye has been left open. However I'll need more information ideally! :)

**Comment by decadence** [comment]
No, I just installed it and it doesn't work as expected from the start.
Ok I'll try to find out if this is a problem of one PC individually.

**Comment by decadence** [comment]
Another PC.
The same situation. What I want
![screenshot_2](https://cloud.githubusercontent.com/assets/1434668/26774621/cadc3012-49d9-11e7-94d9-d03ccad5f98f.png)
and what I get
![screenshot_1](https://cloud.githubusercontent.com/assets/1434668/26774626/cec469d8-49d9-11e7-994d-e65d687629fe.png)

Why it doesn't show new notifications? And it shows many read notifications even if Read filter is not selected.

**Comment by decadence** [comment]
Now I can confirm it doesn't work at all.
Here is my settings
![screenshot_1](https://cloud.githubusercontent.com/assets/1434668/26776630/94b8e81e-49e2-11e7-9150-aff0fcf65cdc.png)

**Comment by andrewhathaway** [comment]
@decadence Read notifications in Hawk Eye are not the same as read on GitHub. Read notifications are still imported, and you'll have to mark them as read. I suggest using Hawk Eye primarily to avoid having to read the same notifications twice. This is because we make sure you don't miss a notification! 

Thanks.

**Comment by decadence** [comment]
Anyway it doesn't work for new notifications properly. For example I subscribed for Symfony repo and have 3 notifications from it on GitHub. Hawk Eye doesn't show anything from it. I am forced to use GitHub further. Anyway thanks.
