### ISSUE TITLE
Cut/copy/paste disabled in GitHub login form window

### ISSUE THREAD

**Issue by jezdez** [harksys/HawkEye#8]
Problem: When I tried to add my GitHub account I wasn't able to paste my password into the password field of the login form.

Expected: Pasting the password.

Found instead: Disabled cut/copy/paste features.

Platform: macOS 10.12.2

**Comment by andrewhathaway** [comment]
Hi @jezdez. Thanks for filing the issue, I'll work on the fix for this this evening.

**Comment by jezdez** [comment]
@andrewhathaway Happy to, thanks for the work on the app!

**Comment by bukinoshita** [comment]
👍 on this issue. I use 1password to store my passwords so I had to type the huge password.

**Comment by andrewhathaway** [comment]
Apologies, this was an oversight by me. Adding a custom Mac menu disabled these features. It'll be pushed out in the next release. :)
